services:
  - type: web
    name: whispering-network
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: whispering-network-db
          property: connectionString

databases:
  - name: whispering-network-db
    plan: free
    databaseName: whispering_network
    user: admin